### ISSUE TITLE
Launchers are not added to the Steam library

### ISSUE THREAD

**Issue by Nick-Reaper** [moraroy/NonSteamLaunchers-On-Steam-Deck#207]
The problem arose after the last update, I checked on GOG, Battle.net and Epic Games, on versions 3.5-3.8, when installing via desktop, the launchers are installed, but are not added to the library, if you use the script directly - the launchers are added, but crookedly - without icons and Games installed through them are not added to the library.

**Comment by moraroy** [comment]
@Nick-Reaper sorry about that brother will continue to look at the coding as alot of code moved recently, thank you for being patient.

**Comment by PS2ClassicsVault** [comment]
i have this sma eisue some will be added while many doesnt get added

**Comment by moraroy** [comment]
@PS2ClassicsVault currently in the process of Migrating alot of Code around, still in that process but things are actually moving along pretty nicely, in the meantime try to read the logs in the download folder and let me know what they say.

**Comment by Skorob0g** [comment]
I am having the same issue, seems like there is something wrong with env variables in NSLGameScanner.py
Here is the excerpt from the logs, if you need some more I can share the whole file in private

```
+ echo 'Starting the service...'
Starting the service...
+ python3 /home/deck/.config/systemd/user/NSLGameScanner.py
steam.sh[12892]: Running Steam on steamos rolling 64-bit
steam.sh[12892]: STEAM_RUNTIME is enabled automatically
setup.sh[13000]: Steam runtime environment up-to-date!
steam.sh[12892]: Steam client's requirements are satisfied
03/16 01:47:41 Init: Installing breakpad exception handler for appid(steam)/version(1710458266)/tid(13052)
Created symlink /home/deck/.config/systemd/user/default.target.wants/nslgamescanner.service → /home/deck/.config/systemd/user/nslgamescanner.service.
['/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
['/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
Service file created.
Service started.
['/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user/Modules', '/home/deck/.config/systemd/user', '/home/deck/Downloads/NonSteamLaunchersInstallation/lib/python3.11/site-packages', '/home/deck', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/lib/python3.11/site-packages']
Traceback (most recent call last):
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 406, in <module>
    create_new_entry(os.environ.get('epicshortcutdirectory'), 'Epic Games', os.environ.get('epiclaunchoptions'), os.environ.get('epicstartingdir'))
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 366, in create_new_entry
    if check_if_shortcut_exists(signed_shortcut_id, appname, exe_path, startingdir, launchoptions):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 324, in check_if_shortcut_exists
    if any(s.get('appid') == shortcut_id for s in shortcuts['shortcuts'].values()):
                                                  ~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'shortcuts'
+ rm -rf /home/deck/Downloads/NonSteamLaunchersInstallation
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
```


There are also some errors regarding the "session bus", I am not sure what it is

```
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 13256
steam-runtime-launcher-service[13256]: E: Can't find session bus: The given address is empty

(steam:13052): libappindicator-WARNING **: 01:47:43.294: Unable to get the session bus: The given address is empty
Steam Runtime Launch Service: steam-runtime-launcher-service pid 13256 exited
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 13425
steam-runtime-launcher-service[13425]: E: Can't find session bus: The given address is empty
Steam Runtime Launch Service: steam-runtime-launcher-service pid 13425 exited
BRefreshApplicationsInLibrary 1: 0ms
Steam Runtime Launch Service: starting steam-runtime-launcher-service
Steam Runtime Launch Service: steam-runtime-launcher-service is running pid 13460
steam-runtime-launcher-service[13460]: E: Can't find session bus: The given address is empty
Steam Runtime Launch Service: steam-runtime-launcher-service pid 13460 exited
Steam Runtime Launch Service: steam-runtime-launcher-service keeps crashing on startup, disabling
BuildCompleteAppOverviewChange: 266 apps
RegisterForAppOverview 1: 13ms
RegisterForAppOverview 2: 14ms
```

I've tried to install Epic Games, GOG & Ubisoft connect. I think that the error with env vars shows only Epic Games b.c. it's the first in the list. After trying to install only GOG I get the same error for it 
```
  File "/home/deck/.config/systemd/user/NSLGameScanner.py", line 407, in <module>
    create_new_entry(os.environ.get('gogshortcutdirectory'), 'Gog Galaxy', os.environ.get('goglaunchoptions'), os.environ.get('gogstartingdir'))
```
