### ISSUE TITLE
Installer stops working after a couple of installations

### ISSUE THREAD

**Issue by danielandross** [moraroy/NonSteamLaunchers-On-Steam-Deck#278]
I am using latest release 3.8.5
I successfully installed a couple of Launchers one by one and they work. 
Then the installer stopped working with any Launcher selected. I can select a new Launcher hit install. It will reopen Steam with the new Item. But when starting the item it will stop after a couple of seconds. When opening the NonSteamInstaller again, that last invalid Launcher does not appear with path ( as the other working launchers do).
Could this be an issue about folder access?
Thanks for that awesome project!

**Comment by moraroy** [comment]
@danielandross yeah there may be an issue in the compatdat folder, may have to check it, currently in the process of rewriting the script, but you should be on the look out for the Decky Plugin Version of NSL, this won't have a lot of the bugs you're encountering.

**Comment by moraroy** [comment]
@danielandross is this fixed with the new version?

**Comment by danielandross** [comment]
@moraroy actually Installation itself worked again without any changes a Few days later. But the install er will not find previously installed launcher paths. Same with New 3.8.7

**Comment by moraroy** [comment]
@danielandross hmm that's not good, can you show me your log?

**Comment by moraroy** [comment]
@danielandross is this still an issue?

**Comment by danielandross** [comment]
Yes. On 3.9.1 I can install a launcher but it will not Show path afterwards

**Comment by moraroy** [comment]
@danielandross can you show your current log? delete any log in the downloads folder and then try to isntall something again so that way i get a fresh log

**Comment by danielandross** [comment]
Hi Roy,
is there any way to send the full log in private?

What I see
`+ wine_registry_path='HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher'
+ registry_keys=(['DisplayName']='Rockstar Games Launcher' ['DisplayIcon']='C:\Program Files\Rockstar Games\Launcher\Launcher.exe, 0' ['DisplayVersion']='1.0.92.2003' ['Publisher']='Rockstar Games' ['InstallLocation']='C:\Program Files\Rockstar Games\Launcher' ['EstimatedSize']='0x00000000' ['UninstallString']='C:\Program Files\Rockstar Games\Launcher\uninstall.exe' ['QuietUninstallString']='"C:\Program Files\Rockstar Games\Launcher\uninstall.exe" /S' ['HelpLink']='https://www.rockstargames.com/support' ['URLInfoAbout']='https://www.rockstargames.com/support' ['URLUpdateInfo']='https://www.rockstargames.com' ['NoModify']='0x1' ['NoRepair']='0x1' ['Comments']='Rockstar Games Launcher' ['Readme']='https://www.rockstargames.com/support')
+ declare -A registry_keys
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v InstallLocation /t REG_SZ /d 'C:\Program Files\Rockstar Games\Launcher' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v Comments /t REG_SZ /d 'Rockstar Games Launcher' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v QuietUninstallString /t REG_SZ /d '"C:\Program Files\Rockstar Games\Launcher\uninstall.exe" /S' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v URLInfoAbout /t REG_SZ /d https://www.rockstargames.com/support /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v UninstallString /t REG_SZ /d 'C:\Program Files\Rockstar Games\Launcher\uninstall.exe' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v NoModify /t REG_SZ /d 0x1 /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v DisplayName /t REG_SZ /d 'Rockstar Games Launcher' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v Publisher /t REG_SZ /d 'Rockstar Games' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v DisplayVersion /t REG_SZ /d 1.0.92.2003 /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v URLUpdateInfo /t REG_SZ /d https://www.rockstargames.com /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v DisplayIcon /t REG_SZ /d 'C:\Program Files\Rockstar Games\Launcher\Launcher.exe, 0' /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v HelpLink /t REG_SZ /d https://www.rockstargames.com/support /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v EstimatedSize /t REG_SZ /d 0x00000000 /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v NoRepair /t REG_SZ /d 0x1 /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ for key in "${!registry_keys[@]}"
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run reg add 'HKEY_LOCAL_MACHINE\Software\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Rockstar Games Launcher' /v Readme /t REG_SZ /d https://www.rockstargames.com/support /f
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files/Rockstar Games/Launcher/Redistributables/VCRed/vc_redist.x64.exe' /install /quiet /norestart
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'
+ /home/deck/.steam/root/ubuntu12_32/steam-runtime/run.sh /home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton run '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx/drive_c/Program Files/Rockstar Games/Launcher/Redistributables/VCRed/vc_redist.x86.exe' /install /quiet /norestart
Traceback (most recent call last):
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1721, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 1600, in init_session
    g_compatdata.setup_prefix()
  File "/home/deck/.steam/root/compatibilitytools.d/GE-Proton9-10/proton", line 876, in setup_prefix
    with self.prefix_lock:
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton9-10/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.local/share/Steam/steamapps/compatdata/NonSteamLaunchers/pfx.lock'`

_I was installing Rockstar Launcher_

`echo 99
+ echo '# Downloading & Installing HoYoPlay...please wait...'
+ [[ Rockstar Games Launcher == *\H\o\Y\o\P\l\a\y* ]]
+ wait
+ echo 99
+ echo '# Checking if Chrome is installed...please wait...'
+ [[ Rockstar Games Launcher == *\N\e\t\f\l\i\x* ]]
+ [[ Rockstar Games Launcher == *\F\o\r\t\n\i\t\e* ]]
+ [[ Rockstar Games Launcher == *\X\b\o\x\ \G\a\m\e\ \P\a\s\s* ]]
+ [[ Rockstar Games Launcher == *\G\e\f\o\r\c\e\ \N\o\w* ]]
+ [[ Rockstar Games Launcher == *\A\m\a\z\o\n\ \L\u\n\a* ]]
+ [[ Rockstar Games Launcher == *\H\u\l\u* ]]
+ [[ Rockstar Games Launcher == *\D\i\s\n\e\y\+* ]]
+ [[ Rockstar Games Launcher == *\A\m\a\z\o\n\ \P\r\i\m\e\ \V\i\d\e\o* ]]
+ [[ Rockstar Games Launcher == *\Y\o\u\t\u\b\e* ]]
+ [[ Rockstar Games Launcher == *\T\w\i\t\c\h* ]]
+ [[ Rockstar Games Launcher == *\m\o\v\i\e\-\w\e\b* ]]
+ wait`

**Comment by moraroy** [comment]
@danielandross you have to upload the whole file on github instead of copy and pasting it

**Comment by danielandross** [comment]
[NonSteamLaunchers-install.log](https://github.com/user-attachments/files/16157983/NonSteamLaunchers-install.log)

**Comment by moraroy** [comment]
@danielandross yeah there is an issue in your compatdata folder make sure there is no broken symlinks if there is please delete them, also please reinstall the latest version of Proton GE

**Comment by danielandross** [comment]
> @danielandross yeah there is an issue in your compatdata folder make sure there is no broken symlinks if there is please delete them, also please reinstall the latest version of Proton GE

Yes that helped. Few reboot later and reinstalling launchers it behaves again as expected. Thank you

**Comment by moraroy** [comment]
@danielandross I would also use the latest .desktop file I updated it yesterday there was another bug in there as well
