### ISSUE TITLE
NSL not adding launchers shortcuts to bazzite

### ISSUE THREAD

**Issue by hyggli** [moraroy/NonSteamLaunchers-On-Steam-Deck#530]
I have bazzite, last version.
I installed decky and now nsl.
I installed the launchers, but they run very fast and the program says they are installed, but no message for the shortcuts.

I can't see them in my steam library anywhere
Any thoughts?

**Comment by moraroy** [comment]
@hyggli I have no idea, as I don't use bazzite , you may have to ask the developer of that program why it's not working haha do you have any logs?

**Comment by crazysmurf** [comment]
@moraroy I ran into same issue. Checked NSL logs. Mainly the distro is missing env_vars:

[2024-12-26 22:40:49,553][ERROR]: Error: /home/bazzite/.config/systemd/user/env_vars does not exist.
[2024-12-26 22:40:49,553][ERROR]: Error handling request
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 477, in _handle_request
  File "aiohttp/web_app.py", line 559, in _handle
  File "/home/bazzite/homebrew/plugins/NonSteamLaunchers/main.py", line 214, in handleCustomSite
    decky_shortcuts = addCustomSite(msg.data)
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/bazzite/homebrew/plugins/NonSteamLaunchers/py_modules/lib/scanner.py", line 132, in addCustomSite
    create_new_entry(env_vars.get('chromedirectory'), customSiteName, chromelaunch_options, env_vars.get('chrome_startdir'), None)
                     ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by moraroy** [comment]
@crazysmurf @hyggli thank you I'll fix soon

**Comment by moraroy** [comment]
@crazysmurf make sure you install a launcher first, this will create the env_vars then try to use the website shortcut

**Comment by crazysmurf** [comment]
@moraroy Tried to install battle.net but same results:



[2024-12-27 14:19:26,199][INFO]: Returning cached update information.
[2024-12-27 14:19:26,220][ERROR]: Missing return statement on request handler
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 653, in finish_response
AttributeError: 'NoneType' object has no attribute 'prepare'
[2024-12-27 14:19:26,220][INFO]: ::1 [27/Dec/2024:14:19:26 -0800] "GET /check_update HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:19:29,862][ERROR]: Missing return statement on request handler
Traceback (most recent call last):
  File "aiohttp/web_protocol.py", line 653, in finish_response
AttributeError: 'NoneType' object has no attribute 'prepare'
[2024-12-27 14:19:29,863][INFO]: ::1 [27/Dec/2024:14:19:29 -0800] "GET /launcher_status HTTP/1.1" 500 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:19:34,144][INFO]: Refreshing environment variables...
[2024-12-27 14:19:34,144][INFO]: Running on Linux or other OS
[2024-12-27 14:19:34,144][ERROR]: Error: /home/bazzite/.config/systemd/user/env_vars does not exist.
[2024-12-27 14:19:34,144][INFO]: No shortcuts to send
[2024-12-27 14:19:56,166][INFO]: Exiting AutoScan loop
[2024-12-27 14:19:56,166][INFO]: ::1 [27/Dec/2024:10:03:11 -0800] "GET /autoscan HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:19:56,166][INFO]: Exiting AutoScan loop
[2024-12-27 14:19:56,166][INFO]: ::1 [27/Dec/2024:10:05:37 -0800] "GET /autoscan HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:19:56,166][INFO]: Exiting AutoScan loop
[2024-12-27 14:19:56,166][INFO]: ::1 [27/Dec/2024:10:27:01 -0800] "GET /autoscan HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:19:56,452][INFO]: install was called
[2024-12-27 14:19:56,452][INFO]: selected_options: BattleNet
[2024-12-27 14:19:56,452][INFO]: separate_app_ids: False
[2024-12-27 14:19:56,452][INFO]: start_fresh: False
[2024-12-27 14:19:56,452][INFO]: install_chrome: False
[2024-12-27 14:19:56,452][INFO]: update_proton_ge: False
[2024-12-27 14:19:56,452][INFO]: nslgamesaves: False
[2024-12-27 14:19:56,452][INFO]: selected_option_nice: Battle.net
[2024-12-27 14:19:56,454][INFO]: Running command: /home/bazzite/homebrew/plugins/NonSteamLaunchers/NonSteamLaunchers.sh " Battle.net" "DeckyPlugin"
[2024-12-27 14:19:56,456][INFO]: Command exit code: 127
[2024-12-27 14:19:56,475][INFO]: Called Manual Scan
[2024-12-27 14:19:56,475][INFO]: Refreshing environment variables...
[2024-12-27 14:19:56,475][INFO]: Running on Linux or other OS
[2024-12-27 14:19:56,475][ERROR]: Error: /home/bazzite/.config/systemd/user/env_vars does not exist.
[2024-12-27 14:19:56,475][INFO]: No shortcuts to send
[2024-12-27 14:19:56,475][INFO]: Running Manual Game Save backup...
[2024-12-27 14:19:56,497][INFO]: Manual Game Save Backup completed
[2024-12-27 14:19:56,497][INFO]: ::1 [27/Dec/2024:14:19:56 -0800] "GET /scan HTTP/1.1" 101 0 "-" "Mozilla/5.0 (X11; Linux x86_64; Valve Steam Client/Steam Deck [Steam Deck Stable]/default/0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36"
[2024-12-27 14:20:01,487][INFO]: AutoScan: True
[2024-12-27 14:20:01,488][INFO]: Refreshing environment variables...
[2024-12-27 14:20:01,488][INFO]: Running on Linux or other OS
[2024-12-27 14:20:01,488][ERROR]: Error: /home/bazzite/.config/systemd/user/env_vars does not exist.
[2024-12-27 14:20:01,488][INFO]: No shortcuts to send

**Comment by crazysmurf** [comment]
Looks like there's a few things missing, so I decide to generate a fresh log. What I did:

Rebooted my linux box into gamescope and went to decky -> nsl -> enable EPIC -> install. Then I went to desktop and attach the whole log file here.


[2024-12-27 14.39.42.log](https://github.com/user-attachments/files/18264168/2024-12-27.14.39.42.log)

**Comment by moraroy** [comment]
@crazysmurf thank you that's helpful, can you also show me a fresh log from trying to install a launcher, I need the specific log from the /home/deck/downloads folder. Since you guys are on bazzite it may look different. From here I can see where it's failing.

**Comment by crazysmurf** [comment]
@moraroy  I don't see anything downloaded to Downloads folder (aside from what i've downloaded). Bazzite distro did a few symlinks, so /home/deck is basically pointing to /var/home/bazzite.

bazzite@bazzite ~> ls -la /home
lrwxrwxrwx. 3 root root 8 Dec  1 21:22 /home -> var/home/

bazzite@bazzite ~> ls -la /var/home/deck
lrwxrwxrwx. 1 root root 13 Dec  1 21:57 /var/home/deck -> /home/bazzite/

bazzite@bazzite ~> ls -la /home/deck/Downloads/
total 24
drwxr-xr-x. 1 bazzite bazzite   150 Dec 27 14:54 ./
drwx------. 1 bazzite bazzite   922 Dec 27 20:14 ../
-rw-r--r--. 1 bazzite bazzite   498 Dec 27 14:27 NonSteamLaunchers.desktop.download
-rwxr--r--. 1 bazzite bazzite   532 Dec 26 22:39 NSLPlugin.desktop.download*
-rw-r--r--. 1 bazzite bazzite 12493 Dec  3 01:54 plex-poster.png

bazzite@bazzite ~> readlink -f /home/deck/Downloads
/var/home/bazzite/Downloads




Is there anywhere else the logs will write to besides /home/bazzite/homebrew/logs? (that's where I pull the fresh launcher install log from)

**Comment by moraroy** [comment]
The only logs for nonsteamlaunchers are located in /home/deck/Downloads and /home/deck/homebrew/logs/NonSteamLaunchers. I see now that if the log itself isn't even being written to, it means the the actual script itself isn't firing. So that's why nothing is installing. Give me some time and I will do my best to gather what I've learned from these logs and I'll see if I can figure out what are the corrects paths on the bazzite distro.

**Comment by crazysmurf** [comment]
@moraroy I've compared the installation on my steam deck vs bazzite and looks like the install on bazzite didnt work correctly. From what I can tell, some files werent installed:

bazzite@bazzite ~/.c/s/user> ls -la
total 4
drwxr-xr-x. 1 bazzite bazzite  48 Dec 11 22:59 ./
drwxr-xr-x. 1 bazzite bazzite   8 Dec 11 22:59 ../
-rw-r--r--. 1 bazzite bazzite 162 Dec 22 00:12 EmuDeckCloudSync.service
bazzite@bazzite ~/.c/s/user> pwd
/home/bazzite/.config/systemd/user


I assume there should be some nsl services that should be here? Is there an install log somewhere I can check? Also, are there any python modules that your code expects but probably wasn't installed?

Let me know what you want me to check.

**Comment by moraroy** [comment]
Are you mainly using the desktop version of NSL or the decky plugin version?

**Comment by crazysmurf** [comment]
@moraroy I use decky plugin version.

Also, just did a quick test on the cli install on epic launcher. That seemed to work. I then go back to "Gaming Mode" (which basically reboots the bazzite and boot into gamescope - big picture). When I go decky -> nsl -> launchers, I see Epic is green. I then ran a manual scan and EPIC shows up on non-steam. I then tried to install/enable streaming services via decky -> nsl and those showed up as non-steam, with the properties filled in, etc (i've enabled netflix, hulu, d+, youtube, etc).

So, it looks like once I've done the first install, things worked. (However, on my steam deck, I went through decky -> nsl to install EPIC and it worked, so something wasn't quite right with bazzite install the first time. btw, bazzite is fedora based)


What I did in CLI:
bazzite@bazzite ~> cd homebrew/plugins/NonSteamLaunchers/
bazzite@bazzite ~/h/p/NonSteamLaunchers> ./NonSteamLaunchers.sh -- "Epic Games"

**Comment by moraroy** [comment]
@crazysmurf the issue that I can see for nsl right now, is some paths don't match up and my logic in how nsl handles the environment variables. Will try my best to fix this very soon, hopefully this will fix that "first run bug" you described, thank you for troubleshooting and being patient

**Comment by crazysmurf** [comment]
@moraroy  no worries. Just strange that I can't install launchers initially when it works perfectly fine on my steam deck. And now after I did the first install via cli, everything works as it should. 

Note that since I have my set up working now, I won't be able to have testing done as quickly, for I'll need to set up another machine to test the scenario.

**Comment by nilsacht** [comment]
Hi, I use the newest Bazzite OS on a ROG Ally and have the same issue.

I tried @crazysmurf solution and installed Epic Games with CLI. It downloaded and installed Proton and in the CLI it says installation is finished. 

Back in game mode and in the nsl plugin i see Epic Games is red. Enable does not work. Reboot the system does nothing.

Is there an other solution or something i missed?

**Comment by hyggli** [comment]
No use for this at all but to give feedbacks on how I managed to get out of the situation.

I thought the system had too much tinkering (not only one time, but every once in a while) and went to Windows+Retrobat+autoplaying retrobat at startup. Now I manage to get everything to work without problems whatsoever.

note: I have a lenovo legion go

**Comment by nilsacht** [comment]
@hyggli so you use Retrobat as GUI for Windows? You can start all games (Steam, Epic, GOG)?

**Comment by moraroy** [comment]
@nilsacht @hyggli @crazysmurf am still working on this. This issue is simply the way the nsl plugin is built, will re-arrange the code to fix the error that's all. No idea what retrobat is.

**Comment by moraroy** [comment]
@crazysmurf @hyggli @nilsacht i be lieve this to be fixed in the current version of the decky plugin please use the NSLPlugin.desktop to confirm
